version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - dbdata:/data/db

  srv_publisher:
    build: ./srv_publisher
    container_name: "publisher"
    depends_on:
      - rabbitmq
    networks:
      - mynetwork
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=phone-book
      - ROUTING_KEY=phone-book

  srv_consumer:
    build: ./srv_consumer
    container_name: "consumer"
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - mynetwork
    restart: always
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ=amqp://guest:guest@rabbitmq:5672/
      - QUEUE_NAME=phone-book
      - ROUTING_KEY=phone-book
      - MONGO_CONNSTRING=mongodb://mongo:27017
      - MONGO_DBNAME=phone-contacts
      - MONGO_COLLECTION_NAME=contacts

  envoy:
    build: Envoy/
    container_name: envoy
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./Envoy/https.crt:/etc/ssl/certs/https.crt
      - ./Envoy/key.pem:/etc/ssl/certs/key.pem
    networks:
      - mynetwork

networks:
  mynetwork:
volumes:
  dbdata:
