version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - dbdata:/data/db

  srv_consumer:
    build: ../
    container_name: "consumer"
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - mynetwork
    restart: always
    environment:
      - RABBITMQ=amqp://guest:guest@rabbitmq:5672/
      - QUEUE_NAME=phone-book
      - MONGO_CONNSTRING=mongodb://mongo:27017
      - MONGO_DBNAME=phone-contacts
      - MONGO_COLLECTION_NAME=contacts

networks:
  mynetwork:
volumes:
  dbdata:
