apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq
  namespace: default
spec:
  secretName: rabbitmq
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: rabbitmq.76673ac1-8c48-4bba-9793-3d09d7d6fc14.lb.civo.com
  dnsNames:
    - rabbitmq.76673ac1-8c48-4bba-9793-3d09d7d6fc14.lb.civo.com
