apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: publisher
  namespace: default
spec:
  secretName: publisher
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: publisher.dnsname
  dnsNames:
    - publisher.dnsname
