version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - local-network

  srv_publisher_local:
    build: "../"
    container_name: "publisher"
    ports:
      - 80:80
    depends_on:
      - rabbitmq
    networks:
      - local-network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=phone-book
      - ROUTING_KEY=phone-book

networks:
  local-network:
