name: Build and Test Services

on: [push]
   
jobs:
  python_service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build and Test
        working-directory: ./srv_publisher
        run: make test

      - name: Clean Workspace
        working-directory: ./srv_publisher
        if: always()
        run: make clean
